
[package]
# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Lists people or organizations that are considered the "authors" of the package.
authors = [spicytechs]

# The title and description fields are primarly for displaying extension info in UI
title = "Varjo OmniGraph Quaternion Rotation"
description="Rotates a quaternion around an angle of the given Euler angles"

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "README.md"

# URL of the extension source repository.
repository="https://github.com/jmake/VarjoOmniGraphQuaternionRotation.git"

# One of categories for UI.
category = "Create"

# Keywords for the extension
keywords = ["kit", "omnigraph"]

# Watch the .ogn files for hot reloading (only works for Python files)
[fswatcher.patterns]
include = ["*.ogn", "*.py"]
exclude = ["Ogn*Database.py"]

[dependencies]
"omni.kit.test" = {}
"omni.graph" = {}

# Main python module this extension provides, it will be publicly available as "import omni.varjo.quaternions".
[[python.module]]
name = "omni.varjo.quaternions"

# Additional python module with tests, to make them discoverable by test system.
[[python.module]]
name = "omni.varjo.quaternions.ogn.tests"


